export const darkTheme = {
   main: `hsl(0, 0%, 12%)`,
   header: `linear-gradient(180deg, hsla(0, 0%, 18%, 1), hsla(0, 0%, 18%, 0.3) 80%, transparent)`,
   chatRoom: `hsl(0, 0%, 18%)`,
   userMessage: `#0c8d71`,
   messageButton: ``,
   formContainer: `hsl(0, 0%, 18%)`,
   form: `hsl(0, 0%, 24%)`,
   formHover: `hsl(0, 0%, 29%)`,
   menuBtn: ``,
   menuBtnHover: ``,
   menu: ``,
   menuListBtns: ``,
   menuListBtnsHover: ``,
   title: `#fff`,
   font: `#fcfcfc`,
   fontDate: `#b6b6b6`,
   settings: `hsl(0, 0%, 16%)`,
   settingsFont: `#f1f1f1`,
   settingsSection: `hsl(0, 0%, 12%)`,
};

export const lightTheme = {
   main: `hsl(0, 0%, 95%)`,
   header: `hsl(0, 0%, 85%)`,
   chatRoom: `hsl(190, 100%, 98%)`,
   messageButton: ``,
   userMessage: `#0c8d71`,
   messageBackground: `hsl(0, 0%, 85%)`,
   formContainer: `hsl(0, 0%, 18%)`,
   form: `hsl(0, 0%, 24%)`,
   formHover: `hsl(0, 0%, 45%)`,
   menuBtn: ``,
   menuBtnHover: ``,
   menu: ``,
   menuListBtns: ``,
   menuListBtnsHover: ``,
   title: ``,
   font: `#2a2e30`,
   fontDate: `hsl(0, 0%, 16%)`,
   settings: ``,
   settingsFont: ``,
   settingsSection: ``,
};
